#import "../block/grid.gql"
#import "../block/hero.gql"
#import "../block/services.gql"
#import "../block/signposts.gql"

fragment PostFields on Post {
  id
  blocks {
    name
    originalContent
    ... on AcfGridBlock {
      ...GridData
    }
    ... on AcfHeroBlock {
      ...HeroData
    }
    ... on AcfServicesBlock {
      ...ServicesData
    }
    ... on AcfSignpostsBlock {
      ...SignpostsData
    }
  }
  revisions {
    nodes {
      id
      blocks {
        name
        originalContent
        ... on AcfGridBlock {
          ...GridData
        }
        ... on AcfHeroBlock {
          ...HeroData
        }
        ... on AcfServicesBlock {
          ...ServicesData
        }
        ... on AcfSignpostsBlock {
          ...SignpostsData
        }
      }
    }
  }
  title
}
